# Generated by Django 3.1.7 on 2021-03-29 10:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('type', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(default='def_M.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Watchmen',
            fields=[
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('image', models.ImageField(blank=True, default='def_M.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
