# Generated by Django 3.1.7 on 2021-03-26 17:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='age',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='name',
        ),
        migrations.RemoveField(
            model_name='watchmen',
            name='age',
        ),
        migrations.RemoveField(
            model_name='watchmen',
            name='name',
        ),
        migrations.AddField(
            model_name='resident',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='watchmen',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
