# Generated by Django 3.1.7 on 2021-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210326_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='watchmen',
            name='dob',
        ),
        migrations.AddField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchmen',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
