# Generated by Django 3.1.7 on 2021-03-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(choices=[('BADM', 'Badminton'), ('TATE', 'Table Tennis'), ('TENS', 'Tennis'), ('COMH', 'Community Hall')], max_length=20)),
                ('status', models.CharField(choices=[('WAIT', 'WAITING FOR APPROVAL'), ('ALOT', 'ALLOTTED'), ('REJC', 'REJECTED')], default='WAIT', max_length=4)),
                ('check_in', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('check_out', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resident')),
            ],
        ),
    ]
