# Generated by Django 3.1.7 on 2021-03-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_directory',
            name='phone_no',
            field=models.IntegerField(default=9709709709),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone_Directory',
        ),
    ]
