# Generated by Django 3.1.7 on 2021-03-29 13:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
