# Generated by Django 3.1.7 on 2021-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('WAIT', 'WAITING FOR APPROVAL'), ('ALOT', 'ALLOTTED'), ('REJC', 'REJECTED')], max_length=4, null=True),
        ),
    ]
