# Generated by Django 3.1.7 on 2021-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('WAIT', 'WAITING FOR APPROVAL'), ('APRV', 'APPROVED'), ('REJC', 'REJECTED')], max_length=4, null=True),
        ),
    ]
